// n8n Code node "Parse Verdict" (exported from the live workflow)
const agentOut = $('AI Agent').first().json.output;
const caseId = $('HTTP Request').first().json._id;

let verdict;
try {
  verdict = JSON.parse(agentOut);
} catch (e) {
  verdict = {
    verdict: "needs_investigation",
    confidence: "low",
    severity: "medium",
    summary: "Agent output could not be parsed. Manual triage required.",
    reasoning: String(agentOut).slice(0, 500),
    escalate: true,
    recommended_next_steps: ["Review raw alert manually"]
  };
}

const sevMap = { critical: 4, high: 3, medium: 2, low: 1, informational: 1 };

const noteBody = [
  `## L1 Agent Triage`,
  ``,
  `**Verdict:** ${verdict.verdict}  (confidence: ${verdict.confidence})`,
  `**Severity:** ${verdict.severity}`,
  `**Class:** ${verdict.alert_class}`,
  `**Escalate:** ${verdict.escalate}`,
  ``,
  `### Summary`,
  verdict.summary,
  ``,
  `### Reasoning`,
  verdict.reasoning,
  ``,
  `### Recommended next steps`,
  ...(verdict.recommended_next_steps || []).map(s => `- ${s}`),
  ``,
  `_Generated by L1 agent. Awaiting analyst approval._`
].join('\n');

return [{
  json: {
    caseId,
    verdict: verdict.verdict,
    severity: verdict.severity,
    sevNumber: sevMap[verdict.severity] || 2,
    escalate: verdict.escalate,
    noteBody
  }
}];
