# logfilename              [owner:group] mode count size(KB) when flags [pid_file]              [sig]
/var/log/dns-queries.log   root:admin    640  7     10240    *    J     /var/run/soc-dnslog.pid  15
/var/log/dns-queries.err   root:admin    640  3     1024     *    JN
